apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    componet: mongodb
    environment: dev
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      componet: mongodb
      environment: dev
      project: roboshop
  template:
    metadata:
      labels:
        componet: mongodb
        environment: dev
        project: roboshop
    spec:
      containers: 
      - name: mongodb
        image: sarthak6700/mongodb:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: roboshop
spec:
  selector:
        componet: mongodb   
        environment: dev
        project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017 # this port belongs to service
    targetPort: 27017 # this port belongs to container