apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true" # keep true in double quotes
  MONGO_URL: "mongodb://mongodb:27017/user"  # protocol//service-name:service-port/schema
  REDIS_HOST: "redis"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
    tier: service
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      tier: service
  template:
    metadata:
      labels:
        app: user
        tier: service
    spec:
      containers:
      - name: user
        image: sarthak6700/user:v1
        ports:
          - containerPort: 8080
            protocol: TCP
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
    tier: service
  name: user
  namespace: roboshop
spec:
  ports:
  - name: user
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: user
    tier: service
  type: ClusterIP
