apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: roboshop
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: db
      project: roboshop
  template:
    metadata:
      labels:
        app: redis
        tier: db
        project: roboshop
    spec:
      containers:
      - name: redis
        image: redis:latest
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: roboshop
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    tier: db
    project: roboshop
  type: ClusterIP
