apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: roboshop
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      proxy_http_version 1.1;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        ssi on;
      }

      location /images/ {
        expires 5s;
        root /usr/share/nginx/html;
        try_files $uri /images/placeholder.png;
      }

      location /api/catalogue/ { proxy_pass http://catalogue:8080/; }
      location /api/user/      { proxy_pass http://user:8080/; }
      location /api/cart/      { proxy_pass http://cart:8080/; }
      location /api/shipping/  { proxy_pass http://shipping:8080/; }
      location /api/payment/   { proxy_pass http://payment:8080/; }

      location /nginx_status {
        stub_status on;
        access_log off;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels: # these labels belong to deployment
    app: web
    tier: web
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: web
      tier: web
      project: roboshop
  template: # this is the pod definition
    metadata:
      labels:
        app: web
        tier: web
        project: roboshop
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx
          items:
          - key: nginx.conf
            path: roboshop.conf
      containers:
      - name: web
        image: sarthak6700/web:v1
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/roboshop.conf
          subPath: roboshop.conf
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: web
    tier: web
    project: roboshop
  ports:
  - name: web-port
    protocol: TCP
    port: 80 # this port belongs to service
    targetPort: 80 # this port belongs to container
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: web
#   namespace: roboshop
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: web
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 75